
title = "Logging operator"

theme = ["docsy"]

baseurl = "/"

# DO NOT DELETE THAT!
_merge = "deep"

enableGitInfo = true

[languages]
[languages.en]
title = "Logging operator"
description = "Documentation for the Logging operator"
languageName ="English"
# Weight used for sorting.
weight = 1

[outputs]
    home = ["HTML", "print"]
    # Enable print this section menu item
    section = [ "HTML", "print" ]

[social]
# Used as twitter:site in page metadata
twitter = "calisti12"

[params]

  email = "mailto:calisti-support@cisco.com"

  # Add project name to the header
  project_name = "Logging operator"
  product_name = "Logging operator"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "4.0.0"
version_menu_canonicallinks = true

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "/"

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "Product page"
    weight = -110
    pre = "<i class='fas fa-rss pr-2'></i>"
    url = "https://calisti.app"
#  [[menu.main]]
#    name = "Blog"
#    weight = -120
#    pre = "<i class='fas fa-blog pr-2'></i>"
#    url = "https://github.com/kube-logging/logging-operator"
  [[menu.main]]
    name = "Documentation"
    weight = -100
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/"
