name: Update generated docs

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'CLI release tag'
        required: true
        type: string

jobs:
  update-generated-docs:
    name: Update generated docs
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup git user
        run: |
          git config --global user.email "build@banzaicloud.com"
          git config --global user.name "banzaicloud-build"

      - name: Update generated docs
        env:
          GITHUB_TOKEN: '${{ secrets.CR_PAT }}'
        run: |
          scripts/update-generated-docs.sh "${{ inputs.release-tag }}"
